ALTER TABLE organizations ADD COLUMN IF NOT EXISTS webhook_url TEXT;

ALTER TABLE servers ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

ALTER TABLE endpoints ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
