/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardOrgIdRouteImport } from './routes/_authenticated/dashboard/$orgId'
import { Route as AuthenticatedDashboardOrgIdServerServerIdRouteImport } from './routes/_authenticated/dashboard/$orgId/server/$serverId'

const AuthenticatedProfileLazyRouteImport = createFileRoute(
  '/_authenticated/profile',
)()
const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const AuthenticatedDashboardOrgIdIndexLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/',
)()
const AuthenticatedDashboardOrgIdUsersLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/users',
)()
const AuthenticatedDashboardOrgIdSettingsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/settings',
)()
const AuthenticatedDashboardOrgIdServersLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/servers',
)()
const AuthenticatedDashboardOrgIdKeysLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/keys',
)()
const AuthenticatedDashboardOrgIdEndpointsLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/endpoints',
)()
const AuthenticatedDashboardOrgIdDatabasesLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard/$orgId/databases',
)()
const AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/$orgId/endpoint/$endpointId')()
const AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRouteImport =
  createFileRoute('/_authenticated/dashboard/$orgId/database/$database')()

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileLazyRoute =
  AuthenticatedProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/profile.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard.lazy').then((d) => d.Route),
  )
const AuthenticatedDashboardOrgIdRoute =
  AuthenticatedDashboardOrgIdRouteImport.update({
    id: '/dashboard/$orgId',
    path: '/dashboard/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardOrgIdIndexLazyRoute =
  AuthenticatedDashboardOrgIdIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdUsersLazyRoute =
  AuthenticatedDashboardOrgIdUsersLazyRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/users.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdSettingsLazyRoute =
  AuthenticatedDashboardOrgIdSettingsLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/settings.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdServersLazyRoute =
  AuthenticatedDashboardOrgIdServersLazyRouteImport.update({
    id: '/servers',
    path: '/servers',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/servers.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdKeysLazyRoute =
  AuthenticatedDashboardOrgIdKeysLazyRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/keys.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdEndpointsLazyRoute =
  AuthenticatedDashboardOrgIdEndpointsLazyRouteImport.update({
    id: '/endpoints',
    path: '/endpoints',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/endpoints.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdDatabasesLazyRoute =
  AuthenticatedDashboardOrgIdDatabasesLazyRouteImport.update({
    id: '/databases',
    path: '/databases',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/databases.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute =
  AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRouteImport.update({
    id: '/endpoint/$endpointId',
    path: '/endpoint/$endpointId',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/endpoint/$endpointId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute =
  AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRouteImport.update({
    id: '/database/$database',
    path: '/database/$database',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/$orgId/database/$database.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedDashboardOrgIdServerServerIdRoute =
  AuthenticatedDashboardOrgIdServerServerIdRouteImport.update({
    id: '/server/$serverId',
    path: '/server/$serverId',
    getParentRoute: () => AuthenticatedDashboardOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/profile': typeof AuthenticatedProfileLazyRoute
  '/dashboard/$orgId': typeof AuthenticatedDashboardOrgIdRouteWithChildren
  '/dashboard/$orgId/databases': typeof AuthenticatedDashboardOrgIdDatabasesLazyRoute
  '/dashboard/$orgId/endpoints': typeof AuthenticatedDashboardOrgIdEndpointsLazyRoute
  '/dashboard/$orgId/keys': typeof AuthenticatedDashboardOrgIdKeysLazyRoute
  '/dashboard/$orgId/servers': typeof AuthenticatedDashboardOrgIdServersLazyRoute
  '/dashboard/$orgId/settings': typeof AuthenticatedDashboardOrgIdSettingsLazyRoute
  '/dashboard/$orgId/users': typeof AuthenticatedDashboardOrgIdUsersLazyRoute
  '/dashboard/$orgId/': typeof AuthenticatedDashboardOrgIdIndexLazyRoute
  '/dashboard/$orgId/server/$serverId': typeof AuthenticatedDashboardOrgIdServerServerIdRoute
  '/dashboard/$orgId/database/$database': typeof AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute
  '/dashboard/$orgId/endpoint/$endpointId': typeof AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/profile': typeof AuthenticatedProfileLazyRoute
  '/dashboard/$orgId/databases': typeof AuthenticatedDashboardOrgIdDatabasesLazyRoute
  '/dashboard/$orgId/endpoints': typeof AuthenticatedDashboardOrgIdEndpointsLazyRoute
  '/dashboard/$orgId/keys': typeof AuthenticatedDashboardOrgIdKeysLazyRoute
  '/dashboard/$orgId/servers': typeof AuthenticatedDashboardOrgIdServersLazyRoute
  '/dashboard/$orgId/settings': typeof AuthenticatedDashboardOrgIdSettingsLazyRoute
  '/dashboard/$orgId/users': typeof AuthenticatedDashboardOrgIdUsersLazyRoute
  '/dashboard/$orgId': typeof AuthenticatedDashboardOrgIdIndexLazyRoute
  '/dashboard/$orgId/server/$serverId': typeof AuthenticatedDashboardOrgIdServerServerIdRoute
  '/dashboard/$orgId/database/$database': typeof AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute
  '/dashboard/$orgId/endpoint/$endpointId': typeof AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileLazyRoute
  '/_authenticated/dashboard/$orgId': typeof AuthenticatedDashboardOrgIdRouteWithChildren
  '/_authenticated/dashboard/$orgId/databases': typeof AuthenticatedDashboardOrgIdDatabasesLazyRoute
  '/_authenticated/dashboard/$orgId/endpoints': typeof AuthenticatedDashboardOrgIdEndpointsLazyRoute
  '/_authenticated/dashboard/$orgId/keys': typeof AuthenticatedDashboardOrgIdKeysLazyRoute
  '/_authenticated/dashboard/$orgId/servers': typeof AuthenticatedDashboardOrgIdServersLazyRoute
  '/_authenticated/dashboard/$orgId/settings': typeof AuthenticatedDashboardOrgIdSettingsLazyRoute
  '/_authenticated/dashboard/$orgId/users': typeof AuthenticatedDashboardOrgIdUsersLazyRoute
  '/_authenticated/dashboard/$orgId/': typeof AuthenticatedDashboardOrgIdIndexLazyRoute
  '/_authenticated/dashboard/$orgId/server/$serverId': typeof AuthenticatedDashboardOrgIdServerServerIdRoute
  '/_authenticated/dashboard/$orgId/database/$database': typeof AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute
  '/_authenticated/dashboard/$orgId/endpoint/$endpointId': typeof AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/dashboard'
    | '/profile'
    | '/dashboard/$orgId'
    | '/dashboard/$orgId/databases'
    | '/dashboard/$orgId/endpoints'
    | '/dashboard/$orgId/keys'
    | '/dashboard/$orgId/servers'
    | '/dashboard/$orgId/settings'
    | '/dashboard/$orgId/users'
    | '/dashboard/$orgId/'
    | '/dashboard/$orgId/server/$serverId'
    | '/dashboard/$orgId/database/$database'
    | '/dashboard/$orgId/endpoint/$endpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/dashboard'
    | '/profile'
    | '/dashboard/$orgId/databases'
    | '/dashboard/$orgId/endpoints'
    | '/dashboard/$orgId/keys'
    | '/dashboard/$orgId/servers'
    | '/dashboard/$orgId/settings'
    | '/dashboard/$orgId/users'
    | '/dashboard/$orgId'
    | '/dashboard/$orgId/server/$serverId'
    | '/dashboard/$orgId/database/$database'
    | '/dashboard/$orgId/endpoint/$endpointId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/dashboard/$orgId'
    | '/_authenticated/dashboard/$orgId/databases'
    | '/_authenticated/dashboard/$orgId/endpoints'
    | '/_authenticated/dashboard/$orgId/keys'
    | '/_authenticated/dashboard/$orgId/servers'
    | '/_authenticated/dashboard/$orgId/settings'
    | '/_authenticated/dashboard/$orgId/users'
    | '/_authenticated/dashboard/$orgId/'
    | '/_authenticated/dashboard/$orgId/server/$serverId'
    | '/_authenticated/dashboard/$orgId/database/$database'
    | '/_authenticated/dashboard/$orgId/endpoint/$endpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$orgId': {
      id: '/_authenticated/dashboard/$orgId'
      path: '/dashboard/$orgId'
      fullPath: '/dashboard/$orgId'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$orgId/': {
      id: '/_authenticated/dashboard/$orgId/'
      path: '/'
      fullPath: '/dashboard/$orgId/'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdIndexLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/users': {
      id: '/_authenticated/dashboard/$orgId/users'
      path: '/users'
      fullPath: '/dashboard/$orgId/users'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdUsersLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/settings': {
      id: '/_authenticated/dashboard/$orgId/settings'
      path: '/settings'
      fullPath: '/dashboard/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdSettingsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/servers': {
      id: '/_authenticated/dashboard/$orgId/servers'
      path: '/servers'
      fullPath: '/dashboard/$orgId/servers'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdServersLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/keys': {
      id: '/_authenticated/dashboard/$orgId/keys'
      path: '/keys'
      fullPath: '/dashboard/$orgId/keys'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdKeysLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/endpoints': {
      id: '/_authenticated/dashboard/$orgId/endpoints'
      path: '/endpoints'
      fullPath: '/dashboard/$orgId/endpoints'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdEndpointsLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/databases': {
      id: '/_authenticated/dashboard/$orgId/databases'
      path: '/databases'
      fullPath: '/dashboard/$orgId/databases'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdDatabasesLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/endpoint/$endpointId': {
      id: '/_authenticated/dashboard/$orgId/endpoint/$endpointId'
      path: '/endpoint/$endpointId'
      fullPath: '/dashboard/$orgId/endpoint/$endpointId'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/database/$database': {
      id: '/_authenticated/dashboard/$orgId/database/$database'
      path: '/database/$database'
      fullPath: '/dashboard/$orgId/database/$database'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
    '/_authenticated/dashboard/$orgId/server/$serverId': {
      id: '/_authenticated/dashboard/$orgId/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/dashboard/$orgId/server/$serverId'
      preLoaderRoute: typeof AuthenticatedDashboardOrgIdServerServerIdRouteImport
      parentRoute: typeof AuthenticatedDashboardOrgIdRoute
    }
  }
}

interface AuthenticatedDashboardOrgIdRouteChildren {
  AuthenticatedDashboardOrgIdDatabasesLazyRoute: typeof AuthenticatedDashboardOrgIdDatabasesLazyRoute
  AuthenticatedDashboardOrgIdEndpointsLazyRoute: typeof AuthenticatedDashboardOrgIdEndpointsLazyRoute
  AuthenticatedDashboardOrgIdKeysLazyRoute: typeof AuthenticatedDashboardOrgIdKeysLazyRoute
  AuthenticatedDashboardOrgIdServersLazyRoute: typeof AuthenticatedDashboardOrgIdServersLazyRoute
  AuthenticatedDashboardOrgIdSettingsLazyRoute: typeof AuthenticatedDashboardOrgIdSettingsLazyRoute
  AuthenticatedDashboardOrgIdUsersLazyRoute: typeof AuthenticatedDashboardOrgIdUsersLazyRoute
  AuthenticatedDashboardOrgIdIndexLazyRoute: typeof AuthenticatedDashboardOrgIdIndexLazyRoute
  AuthenticatedDashboardOrgIdServerServerIdRoute: typeof AuthenticatedDashboardOrgIdServerServerIdRoute
  AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute: typeof AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute
  AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute: typeof AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute
}

const AuthenticatedDashboardOrgIdRouteChildren: AuthenticatedDashboardOrgIdRouteChildren =
  {
    AuthenticatedDashboardOrgIdDatabasesLazyRoute:
      AuthenticatedDashboardOrgIdDatabasesLazyRoute,
    AuthenticatedDashboardOrgIdEndpointsLazyRoute:
      AuthenticatedDashboardOrgIdEndpointsLazyRoute,
    AuthenticatedDashboardOrgIdKeysLazyRoute:
      AuthenticatedDashboardOrgIdKeysLazyRoute,
    AuthenticatedDashboardOrgIdServersLazyRoute:
      AuthenticatedDashboardOrgIdServersLazyRoute,
    AuthenticatedDashboardOrgIdSettingsLazyRoute:
      AuthenticatedDashboardOrgIdSettingsLazyRoute,
    AuthenticatedDashboardOrgIdUsersLazyRoute:
      AuthenticatedDashboardOrgIdUsersLazyRoute,
    AuthenticatedDashboardOrgIdIndexLazyRoute:
      AuthenticatedDashboardOrgIdIndexLazyRoute,
    AuthenticatedDashboardOrgIdServerServerIdRoute:
      AuthenticatedDashboardOrgIdServerServerIdRoute,
    AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute:
      AuthenticatedDashboardOrgIdDatabaseDatabaseLazyRoute,
    AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute:
      AuthenticatedDashboardOrgIdEndpointEndpointIdLazyRoute,
  }

const AuthenticatedDashboardOrgIdRouteWithChildren =
  AuthenticatedDashboardOrgIdRoute._addFileChildren(
    AuthenticatedDashboardOrgIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedProfileLazyRoute: typeof AuthenticatedProfileLazyRoute
  AuthenticatedDashboardOrgIdRoute: typeof AuthenticatedDashboardOrgIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedProfileLazyRoute: AuthenticatedProfileLazyRoute,
  AuthenticatedDashboardOrgIdRoute:
    AuthenticatedDashboardOrgIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
